// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: simple.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HelloSayer_SayHello_FullMethodName = "/HelloSayer/SayHello"
)

// HelloSayerClient is the client API for HelloSayer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloSayerClient interface {
	SayHello(ctx context.Context, in *HelloMessage, opts ...grpc.CallOption) (*HelloReply, error)
}

type helloSayerClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloSayerClient(cc grpc.ClientConnInterface) HelloSayerClient {
	return &helloSayerClient{cc}
}

func (c *helloSayerClient) SayHello(ctx context.Context, in *HelloMessage, opts ...grpc.CallOption) (*HelloReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, HelloSayer_SayHello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloSayerServer is the server API for HelloSayer service.
// All implementations must embed UnimplementedHelloSayerServer
// for forward compatibility.
type HelloSayerServer interface {
	SayHello(context.Context, *HelloMessage) (*HelloReply, error)
	mustEmbedUnimplementedHelloSayerServer()
}

// UnimplementedHelloSayerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHelloSayerServer struct{}

func (UnimplementedHelloSayerServer) SayHello(context.Context, *HelloMessage) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedHelloSayerServer) mustEmbedUnimplementedHelloSayerServer() {}
func (UnimplementedHelloSayerServer) testEmbeddedByValue()                    {}

// UnsafeHelloSayerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloSayerServer will
// result in compilation errors.
type UnsafeHelloSayerServer interface {
	mustEmbedUnimplementedHelloSayerServer()
}

func RegisterHelloSayerServer(s grpc.ServiceRegistrar, srv HelloSayerServer) {
	// If the following call pancis, it indicates UnimplementedHelloSayerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HelloSayer_ServiceDesc, srv)
}

func _HelloSayer_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloSayerServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HelloSayer_SayHello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloSayerServer).SayHello(ctx, req.(*HelloMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// HelloSayer_ServiceDesc is the grpc.ServiceDesc for HelloSayer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloSayer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HelloSayer",
	HandlerType: (*HelloSayerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloSayer_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "simple.proto",
}
